<?php
/**
 * EntityAuthorizationGrant
 *
 * PHP version 8.1
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API TE
 *
 * **Wersja API:** 2.0.0 (build 2.0.0-rc5.7-te-20251115.1+12de7e512c6dede0af882fee4f7e52fc04590ab4)<br> **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br> **Historia zmian:** [Changelog](https://github.com/CIRFMF/ksef-docs/blob/main/api-changelog.md)<br> **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 * The version of the OpenAPI document: v2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NetSeven\KseF2Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use NetSeven\ObjectSerializer;

/**
 * EntityAuthorizationGrant Class Doc Comment
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class EntityAuthorizationGrant implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'EntityAuthorizationGrant';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'string',
        'author_identifier' => '\NetSeven\KseF2Model\EntityAuthorizationsAuthorIdentifier',
        'authorized_entity_identifier' => '\NetSeven\KseF2Model\EntityAuthorizationsAuthorizedEntityIdentifier',
        'authorizing_entity_identifier' => '\NetSeven\KseF2Model\EntityAuthorizationsAuthorizingEntityIdentifier',
        'authorization_scope' => '\NetSeven\KseF2Model\InvoicePermissionType',
        'description' => 'string',
        'start_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => null,
        'author_identifier' => null,
        'authorized_entity_identifier' => null,
        'authorizing_entity_identifier' => null,
        'authorization_scope' => null,
        'description' => null,
        'start_date' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => false,
        'author_identifier' => true,
        'authorized_entity_identifier' => false,
        'authorizing_entity_identifier' => false,
        'authorization_scope' => false,
        'description' => false,
        'start_date' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'author_identifier' => 'authorIdentifier',
        'authorized_entity_identifier' => 'authorizedEntityIdentifier',
        'authorizing_entity_identifier' => 'authorizingEntityIdentifier',
        'authorization_scope' => 'authorizationScope',
        'description' => 'description',
        'start_date' => 'startDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'author_identifier' => 'setAuthorIdentifier',
        'authorized_entity_identifier' => 'setAuthorizedEntityIdentifier',
        'authorizing_entity_identifier' => 'setAuthorizingEntityIdentifier',
        'authorization_scope' => 'setAuthorizationScope',
        'description' => 'setDescription',
        'start_date' => 'setStartDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'author_identifier' => 'getAuthorIdentifier',
        'authorized_entity_identifier' => 'getAuthorizedEntityIdentifier',
        'authorizing_entity_identifier' => 'getAuthorizingEntityIdentifier',
        'authorization_scope' => 'getAuthorizationScope',
        'description' => 'getDescription',
        'start_date' => 'getStartDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('author_identifier', $data ?? [], null);
        $this->setIfExists('authorized_entity_identifier', $data ?? [], null);
        $this->setIfExists('authorizing_entity_identifier', $data ?? [], null);
        $this->setIfExists('authorization_scope', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('start_date', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ((mb_strlen($this->container['id']) > 36)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be smaller than or equal to 36.";
        }

        if ((mb_strlen($this->container['id']) < 36)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be bigger than or equal to 36.";
        }

        if ($this->container['authorized_entity_identifier'] === null) {
            $invalidProperties[] = "'authorized_entity_identifier' can't be null";
        }
        if ($this->container['authorizing_entity_identifier'] === null) {
            $invalidProperties[] = "'authorizing_entity_identifier' can't be null";
        }
        if ($this->container['authorization_scope'] === null) {
            $invalidProperties[] = "'authorization_scope' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ((mb_strlen($this->container['description']) > 256)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 256.";
        }

        if ((mb_strlen($this->container['description']) < 5)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be bigger than or equal to 5.";
        }

        if ($this->container['start_date'] === null) {
            $invalidProperties[] = "'start_date' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Identyfikator uprawnienia.
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        if ((mb_strlen($id) > 36)) {
            throw new InvalidArgumentException('invalid length for $id when calling EntityAuthorizationGrant., must be smaller than or equal to 36.');
        }
        if ((mb_strlen($id) < 36)) {
            throw new InvalidArgumentException('invalid length for $id when calling EntityAuthorizationGrant., must be bigger than or equal to 36.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets author_identifier
     *
     * @return \NetSeven\KseF2Model\EntityAuthorizationsAuthorIdentifier|null
     */
    public function getAuthorIdentifier(): ?\NetSeven\KseF2Model\EntityAuthorizationsAuthorIdentifier
    {
        return $this->container['author_identifier'];
    }

    /**
     * Sets author_identifier
     *
     * @param \NetSeven\KseF2Model\EntityAuthorizationsAuthorIdentifier|null $author_identifier Identyfikator osoby nadającej uprawnienie. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu |
     *
     * @return $this
     */
    public function setAuthorIdentifier(?\NetSeven\KseF2Model\EntityAuthorizationsAuthorIdentifier $author_identifier): static
    {
        if (is_null($author_identifier)) {
            array_push($this->openAPINullablesSetToNull, 'author_identifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('author_identifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['author_identifier'] = $author_identifier;

        return $this;
    }

    /**
     * Gets authorized_entity_identifier
     *
     * @return \NetSeven\KseF2Model\EntityAuthorizationsAuthorizedEntityIdentifier
     */
    public function getAuthorizedEntityIdentifier(): \NetSeven\KseF2Model\EntityAuthorizationsAuthorizedEntityIdentifier
    {
        return $this->container['authorized_entity_identifier'];
    }

    /**
     * Sets authorized_entity_identifier
     *
     * @param \NetSeven\KseF2Model\EntityAuthorizationsAuthorizedEntityIdentifier $authorized_entity_identifier Identyfikator podmiotu uprawnionego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | PeppolId | Identyfikator dostawcy usług Peppol |
     *
     * @return $this
     */
    public function setAuthorizedEntityIdentifier(\NetSeven\KseF2Model\EntityAuthorizationsAuthorizedEntityIdentifier $authorized_entity_identifier): static
    {
        if (is_null($authorized_entity_identifier)) {
            throw new InvalidArgumentException('non-nullable authorized_entity_identifier cannot be null');
        }
        $this->container['authorized_entity_identifier'] = $authorized_entity_identifier;

        return $this;
    }

    /**
     * Gets authorizing_entity_identifier
     *
     * @return \NetSeven\KseF2Model\EntityAuthorizationsAuthorizingEntityIdentifier
     */
    public function getAuthorizingEntityIdentifier(): \NetSeven\KseF2Model\EntityAuthorizationsAuthorizingEntityIdentifier
    {
        return $this->container['authorizing_entity_identifier'];
    }

    /**
     * Sets authorizing_entity_identifier
     *
     * @param \NetSeven\KseF2Model\EntityAuthorizationsAuthorizingEntityIdentifier $authorizing_entity_identifier Identyfikator podmiotu uprawniającego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP |
     *
     * @return $this
     */
    public function setAuthorizingEntityIdentifier(\NetSeven\KseF2Model\EntityAuthorizationsAuthorizingEntityIdentifier $authorizing_entity_identifier): static
    {
        if (is_null($authorizing_entity_identifier)) {
            throw new InvalidArgumentException('non-nullable authorizing_entity_identifier cannot be null');
        }
        $this->container['authorizing_entity_identifier'] = $authorizing_entity_identifier;

        return $this;
    }

    /**
     * Gets authorization_scope
     *
     * @return \NetSeven\KseF2Model\InvoicePermissionType
     */
    public function getAuthorizationScope(): \NetSeven\KseF2Model\InvoicePermissionType
    {
        return $this->container['authorization_scope'];
    }

    /**
     * Sets authorization_scope
     *
     * @param \NetSeven\KseF2Model\InvoicePermissionType $authorization_scope Rodzaj uprawnienia.
     *
     * @return $this
     */
    public function setAuthorizationScope(\NetSeven\KseF2Model\InvoicePermissionType $authorization_scope): static
    {
        if (is_null($authorization_scope)) {
            throw new InvalidArgumentException('non-nullable authorization_scope cannot be null');
        }
        $this->container['authorization_scope'] = $authorization_scope;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription(): string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description Opis uprawnienia.
     *
     * @return $this
     */
    public function setDescription(string $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 256)) {
            throw new InvalidArgumentException('invalid length for $description when calling EntityAuthorizationGrant., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($description) < 5)) {
            throw new InvalidArgumentException('invalid length for $description when calling EntityAuthorizationGrant., must be bigger than or equal to 5.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets start_date
     *
     * @return \DateTime
     */
    public function getStartDate(): \DateTime
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     *
     * @param \DateTime $start_date Data rozpoczęcia obowiązywania uprawnienia.
     *
     * @return $this
     */
    public function setStartDate(\DateTime $start_date): static
    {
        if (is_null($start_date)) {
            throw new InvalidArgumentException('non-nullable start_date cannot be null');
        }
        $this->container['start_date'] = $start_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


