<?php
/**
 * EntityAuthorizationPermissionsQueryRequest
 *
 * PHP version 8.1
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API TE
 *
 * **Wersja API:** 2.0.0 (build 2.0.0-rc5.7-te-20251115.1+12de7e512c6dede0af882fee4f7e52fc04590ab4)<br> **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br> **Historia zmian:** [Changelog](https://github.com/CIRFMF/ksef-docs/blob/main/api-changelog.md)<br> **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 * The version of the OpenAPI document: v2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NetSeven\KseF2Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use NetSeven\ObjectSerializer;

/**
 * EntityAuthorizationPermissionsQueryRequest Class Doc Comment
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class EntityAuthorizationPermissionsQueryRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'EntityAuthorizationPermissionsQueryRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'authorizing_identifier' => '\NetSeven\KseF2Model\EntityAuthorizationsAuthorizingEntityIdentifier',
        'authorized_identifier' => '\NetSeven\KseF2Model\EntityAuthorizationsAuthorizedEntityIdentifier',
        'query_type' => '\NetSeven\KseF2Model\QueryType',
        'permission_types' => '\NetSeven\KseF2Model\InvoicePermissionType[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'authorizing_identifier' => null,
        'authorized_identifier' => null,
        'query_type' => null,
        'permission_types' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'authorizing_identifier' => true,
        'authorized_identifier' => true,
        'query_type' => false,
        'permission_types' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'authorizing_identifier' => 'authorizingIdentifier',
        'authorized_identifier' => 'authorizedIdentifier',
        'query_type' => 'queryType',
        'permission_types' => 'permissionTypes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'authorizing_identifier' => 'setAuthorizingIdentifier',
        'authorized_identifier' => 'setAuthorizedIdentifier',
        'query_type' => 'setQueryType',
        'permission_types' => 'setPermissionTypes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'authorizing_identifier' => 'getAuthorizingIdentifier',
        'authorized_identifier' => 'getAuthorizedIdentifier',
        'query_type' => 'getQueryType',
        'permission_types' => 'getPermissionTypes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('authorizing_identifier', $data ?? [], null);
        $this->setIfExists('authorized_identifier', $data ?? [], null);
        $this->setIfExists('query_type', $data ?? [], null);
        $this->setIfExists('permission_types', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['query_type'] === null) {
            $invalidProperties[] = "'query_type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets authorizing_identifier
     *
     * @return \NetSeven\KseF2Model\EntityAuthorizationsAuthorizingEntityIdentifier|null
     */
    public function getAuthorizingIdentifier(): ?\NetSeven\KseF2Model\EntityAuthorizationsAuthorizingEntityIdentifier
    {
        return $this->container['authorizing_identifier'];
    }

    /**
     * Sets authorizing_identifier
     *
     * @param \NetSeven\KseF2Model\EntityAuthorizationsAuthorizingEntityIdentifier|null $authorizing_identifier Identyfikator podmiotu uprawniającego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP |
     *
     * @return $this
     */
    public function setAuthorizingIdentifier(?\NetSeven\KseF2Model\EntityAuthorizationsAuthorizingEntityIdentifier $authorizing_identifier): static
    {
        if (is_null($authorizing_identifier)) {
            array_push($this->openAPINullablesSetToNull, 'authorizing_identifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorizing_identifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorizing_identifier'] = $authorizing_identifier;

        return $this;
    }

    /**
     * Gets authorized_identifier
     *
     * @return \NetSeven\KseF2Model\EntityAuthorizationsAuthorizedEntityIdentifier|null
     */
    public function getAuthorizedIdentifier(): ?\NetSeven\KseF2Model\EntityAuthorizationsAuthorizedEntityIdentifier
    {
        return $this->container['authorized_identifier'];
    }

    /**
     * Sets authorized_identifier
     *
     * @param \NetSeven\KseF2Model\EntityAuthorizationsAuthorizedEntityIdentifier|null $authorized_identifier Identyfikator podmiotu uprawnionego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | PeppolId | Identyfikator dostawcy usług Peppol |
     *
     * @return $this
     */
    public function setAuthorizedIdentifier(?\NetSeven\KseF2Model\EntityAuthorizationsAuthorizedEntityIdentifier $authorized_identifier): static
    {
        if (is_null($authorized_identifier)) {
            array_push($this->openAPINullablesSetToNull, 'authorized_identifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorized_identifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorized_identifier'] = $authorized_identifier;

        return $this;
    }

    /**
     * Gets query_type
     *
     * @return \NetSeven\KseF2Model\QueryType
     */
    public function getQueryType(): \NetSeven\KseF2Model\QueryType
    {
        return $this->container['query_type'];
    }

    /**
     * Sets query_type
     *
     * @param \NetSeven\KseF2Model\QueryType $query_type Typ zapytania. | Type | Value | | --- | --- | | Granted | Uprawnienia nadane innym podmiotom | | Received | Uprawnienia otrzymane od innych podmiotów |
     *
     * @return $this
     */
    public function setQueryType(\NetSeven\KseF2Model\QueryType $query_type): static
    {
        if (is_null($query_type)) {
            throw new InvalidArgumentException('non-nullable query_type cannot be null');
        }
        $this->container['query_type'] = $query_type;

        return $this;
    }

    /**
     * Gets permission_types
     *
     * @return \NetSeven\KseF2Model\InvoicePermissionType[]|null
     */
    public function getPermissionTypes(): ?array
    {
        return $this->container['permission_types'];
    }

    /**
     * Sets permission_types
     *
     * @param \NetSeven\KseF2Model\InvoicePermissionType[]|null $permission_types Lista rodzajów wyszukiwanych uprawnień.
     *
     * @return $this
     */
    public function setPermissionTypes(?array $permission_types): static
    {
        if (is_null($permission_types)) {
            array_push($this->openAPINullablesSetToNull, 'permission_types');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('permission_types', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['permission_types'] = $permission_types;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


