<?php
/**
 * InvoicePackage
 *
 * PHP version 8.1
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API TE
 *
 * **Wersja API:** 2.0.0 (build 2.0.0-rc5.7-te-20251115.1+12de7e512c6dede0af882fee4f7e52fc04590ab4)<br> **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br> **Historia zmian:** [Changelog](https://github.com/CIRFMF/ksef-docs/blob/main/api-changelog.md)<br> **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 * The version of the OpenAPI document: v2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NetSeven\KseF2Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use NetSeven\ObjectSerializer;

/**
 * InvoicePackage Class Doc Comment
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class InvoicePackage implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'InvoicePackage';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'invoice_count' => 'int',
        'size' => 'int',
        'parts' => '\NetSeven\KseF2Model\InvoicePackagePart[]',
        'is_truncated' => 'bool',
        'last_issue_date' => '\DateTime',
        'last_invoicing_date' => '\DateTime',
        'last_permanent_storage_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'invoice_count' => 'int64',
        'size' => 'int64',
        'parts' => null,
        'is_truncated' => null,
        'last_issue_date' => 'date',
        'last_invoicing_date' => 'date-time',
        'last_permanent_storage_date' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'invoice_count' => false,
        'size' => false,
        'parts' => false,
        'is_truncated' => false,
        'last_issue_date' => true,
        'last_invoicing_date' => true,
        'last_permanent_storage_date' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'invoice_count' => 'invoiceCount',
        'size' => 'size',
        'parts' => 'parts',
        'is_truncated' => 'isTruncated',
        'last_issue_date' => 'lastIssueDate',
        'last_invoicing_date' => 'lastInvoicingDate',
        'last_permanent_storage_date' => 'lastPermanentStorageDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'invoice_count' => 'setInvoiceCount',
        'size' => 'setSize',
        'parts' => 'setParts',
        'is_truncated' => 'setIsTruncated',
        'last_issue_date' => 'setLastIssueDate',
        'last_invoicing_date' => 'setLastInvoicingDate',
        'last_permanent_storage_date' => 'setLastPermanentStorageDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'invoice_count' => 'getInvoiceCount',
        'size' => 'getSize',
        'parts' => 'getParts',
        'is_truncated' => 'getIsTruncated',
        'last_issue_date' => 'getLastIssueDate',
        'last_invoicing_date' => 'getLastInvoicingDate',
        'last_permanent_storage_date' => 'getLastPermanentStorageDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('invoice_count', $data ?? [], null);
        $this->setIfExists('size', $data ?? [], null);
        $this->setIfExists('parts', $data ?? [], null);
        $this->setIfExists('is_truncated', $data ?? [], null);
        $this->setIfExists('last_issue_date', $data ?? [], null);
        $this->setIfExists('last_invoicing_date', $data ?? [], null);
        $this->setIfExists('last_permanent_storage_date', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['invoice_count'] === null) {
            $invalidProperties[] = "'invoice_count' can't be null";
        }
        if (($this->container['invoice_count'] > 10000)) {
            $invalidProperties[] = "invalid value for 'invoice_count', must be smaller than or equal to 10000.";
        }

        if (($this->container['invoice_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'invoice_count', must be bigger than or equal to 0.";
        }

        if ($this->container['size'] === null) {
            $invalidProperties[] = "'size' can't be null";
        }
        if (($this->container['size'] < 0)) {
            $invalidProperties[] = "invalid value for 'size', must be bigger than or equal to 0.";
        }

        if ($this->container['parts'] === null) {
            $invalidProperties[] = "'parts' can't be null";
        }
        if ($this->container['is_truncated'] === null) {
            $invalidProperties[] = "'is_truncated' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets invoice_count
     *
     * @return int
     */
    public function getInvoiceCount(): int
    {
        return $this->container['invoice_count'];
    }

    /**
     * Sets invoice_count
     *
     * @param int $invoice_count Łączna liczba faktur w paczce.
     *
     * @return $this
     */
    public function setInvoiceCount(int $invoice_count): static
    {
        if (is_null($invoice_count)) {
            throw new InvalidArgumentException('non-nullable invoice_count cannot be null');
        }

        if (($invoice_count > 10000)) {
            throw new InvalidArgumentException('invalid value for $invoice_count when calling InvoicePackage., must be smaller than or equal to 10000.');
        }
        if (($invoice_count < 0)) {
            throw new InvalidArgumentException('invalid value for $invoice_count when calling InvoicePackage., must be bigger than or equal to 0.');
        }

        $this->container['invoice_count'] = $invoice_count;

        return $this;
    }

    /**
     * Gets size
     *
     * @return int
     */
    public function getSize(): int
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param int $size Rozmiar paczki w bajtach.
     *
     * @return $this
     */
    public function setSize(int $size): static
    {
        if (is_null($size)) {
            throw new InvalidArgumentException('non-nullable size cannot be null');
        }

        if (($size < 0)) {
            throw new InvalidArgumentException('invalid value for $size when calling InvoicePackage., must be bigger than or equal to 0.');
        }

        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets parts
     *
     * @return \NetSeven\KseF2Model\InvoicePackagePart[]
     */
    public function getParts(): array
    {
        return $this->container['parts'];
    }

    /**
     * Sets parts
     *
     * @param \NetSeven\KseF2Model\InvoicePackagePart[] $parts Lista dostępnych części paczki do pobrania.
     *
     * @return $this
     */
    public function setParts(array $parts): static
    {
        if (is_null($parts)) {
            throw new InvalidArgumentException('non-nullable parts cannot be null');
        }
        $this->container['parts'] = $parts;

        return $this;
    }

    /**
     * Gets is_truncated
     *
     * @return bool
     */
    public function getIsTruncated(): bool
    {
        return $this->container['is_truncated'];
    }

    /**
     * Sets is_truncated
     *
     * @param bool $is_truncated Określa, czy wynik eksportu został ucięty z powodu przekroczenia limitu liczby faktur lub wielkości paczki.
     *
     * @return $this
     */
    public function setIsTruncated(bool $is_truncated): static
    {
        if (is_null($is_truncated)) {
            throw new InvalidArgumentException('non-nullable is_truncated cannot be null');
        }
        $this->container['is_truncated'] = $is_truncated;

        return $this;
    }

    /**
     * Gets last_issue_date
     *
     * @return \DateTime|null
     */
    public function getLastIssueDate(): ?\DateTime
    {
        return $this->container['last_issue_date'];
    }

    /**
     * Sets last_issue_date
     *
     * @param \DateTime|null $last_issue_date Data wystawienia ostatniej faktury ujętej w paczce. Pole występuje wyłącznie wtedy, gdy paczka została ucięta i eksport był filtrowany po typie daty `Issue`.
     *
     * @return $this
     */
    public function setLastIssueDate(?\DateTime $last_issue_date): static
    {
        if (is_null($last_issue_date)) {
            array_push($this->openAPINullablesSetToNull, 'last_issue_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_issue_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_issue_date'] = $last_issue_date;

        return $this;
    }

    /**
     * Gets last_invoicing_date
     *
     * @return \DateTime|null
     */
    public function getLastInvoicingDate(): ?\DateTime
    {
        return $this->container['last_invoicing_date'];
    }

    /**
     * Sets last_invoicing_date
     *
     * @param \DateTime|null $last_invoicing_date Data przyjęcia ostatniej faktury ujętej w paczce. Pole występuje wyłącznie wtedy, gdy paczka została ucięta i eksport był filtrowany po typie daty `Invoicing`.
     *
     * @return $this
     */
    public function setLastInvoicingDate(?\DateTime $last_invoicing_date): static
    {
        if (is_null($last_invoicing_date)) {
            array_push($this->openAPINullablesSetToNull, 'last_invoicing_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_invoicing_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_invoicing_date'] = $last_invoicing_date;

        return $this;
    }

    /**
     * Gets last_permanent_storage_date
     *
     * @return \DateTime|null
     */
    public function getLastPermanentStorageDate(): ?\DateTime
    {
        return $this->container['last_permanent_storage_date'];
    }

    /**
     * Sets last_permanent_storage_date
     *
     * @param \DateTime|null $last_permanent_storage_date Data trwałego zapisu ostatniej faktury ujętej w paczce. Pole występuje wyłącznie wtedy, gdy paczka została ucięta i eksport był filtrowany po typie daty `PermanentStorage`.
     *
     * @return $this
     */
    public function setLastPermanentStorageDate(?\DateTime $last_permanent_storage_date): static
    {
        if (is_null($last_permanent_storage_date)) {
            array_push($this->openAPINullablesSetToNull, 'last_permanent_storage_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_permanent_storage_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_permanent_storage_date'] = $last_permanent_storage_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


