<?php
/**
 * InvoiceQueryFilters
 *
 * PHP version 8.1
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API TE
 *
 * **Wersja API:** 2.0.0 (build 2.0.0-rc5.7-te-20251115.1+12de7e512c6dede0af882fee4f7e52fc04590ab4)<br> **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br> **Historia zmian:** [Changelog](https://github.com/CIRFMF/ksef-docs/blob/main/api-changelog.md)<br> **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 * The version of the OpenAPI document: v2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NetSeven\KseF2Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use NetSeven\ObjectSerializer;

/**
 * InvoiceQueryFilters Class Doc Comment
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class InvoiceQueryFilters implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'InvoiceQueryFilters';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'subject_type' => '\NetSeven\KseF2Model\InvoiceQuerySubjectType',
        'date_range' => '\NetSeven\KseF2Model\InvoiceQueryDateRange',
        'ksef_number' => 'string',
        'invoice_number' => 'string',
        'amount' => '\NetSeven\KseF2Model\InvoiceQueryAmount',
        'seller_nip' => 'string',
        'buyer_identifier' => '\NetSeven\KseF2Model\InvoiceQueryBuyerIdentifier',
        'currency_codes' => '\NetSeven\KseF2Model\CurrencyCode[]',
        'invoicing_mode' => '\NetSeven\KseF2Model\InvoicingMode',
        'is_self_invoicing' => 'bool',
        'form_type' => '\NetSeven\KseF2Model\InvoiceQueryFormType',
        'invoice_types' => '\NetSeven\KseF2Model\InvoiceType[]',
        'has_attachment' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'subject_type' => null,
        'date_range' => null,
        'ksef_number' => null,
        'invoice_number' => null,
        'amount' => null,
        'seller_nip' => null,
        'buyer_identifier' => null,
        'currency_codes' => null,
        'invoicing_mode' => null,
        'is_self_invoicing' => null,
        'form_type' => null,
        'invoice_types' => null,
        'has_attachment' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'subject_type' => false,
        'date_range' => false,
        'ksef_number' => true,
        'invoice_number' => true,
        'amount' => true,
        'seller_nip' => true,
        'buyer_identifier' => true,
        'currency_codes' => true,
        'invoicing_mode' => true,
        'is_self_invoicing' => true,
        'form_type' => true,
        'invoice_types' => true,
        'has_attachment' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'subject_type' => 'subjectType',
        'date_range' => 'dateRange',
        'ksef_number' => 'ksefNumber',
        'invoice_number' => 'invoiceNumber',
        'amount' => 'amount',
        'seller_nip' => 'sellerNip',
        'buyer_identifier' => 'buyerIdentifier',
        'currency_codes' => 'currencyCodes',
        'invoicing_mode' => 'invoicingMode',
        'is_self_invoicing' => 'isSelfInvoicing',
        'form_type' => 'formType',
        'invoice_types' => 'invoiceTypes',
        'has_attachment' => 'hasAttachment'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'subject_type' => 'setSubjectType',
        'date_range' => 'setDateRange',
        'ksef_number' => 'setKsefNumber',
        'invoice_number' => 'setInvoiceNumber',
        'amount' => 'setAmount',
        'seller_nip' => 'setSellerNip',
        'buyer_identifier' => 'setBuyerIdentifier',
        'currency_codes' => 'setCurrencyCodes',
        'invoicing_mode' => 'setInvoicingMode',
        'is_self_invoicing' => 'setIsSelfInvoicing',
        'form_type' => 'setFormType',
        'invoice_types' => 'setInvoiceTypes',
        'has_attachment' => 'setHasAttachment'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'subject_type' => 'getSubjectType',
        'date_range' => 'getDateRange',
        'ksef_number' => 'getKsefNumber',
        'invoice_number' => 'getInvoiceNumber',
        'amount' => 'getAmount',
        'seller_nip' => 'getSellerNip',
        'buyer_identifier' => 'getBuyerIdentifier',
        'currency_codes' => 'getCurrencyCodes',
        'invoicing_mode' => 'getInvoicingMode',
        'is_self_invoicing' => 'getIsSelfInvoicing',
        'form_type' => 'getFormType',
        'invoice_types' => 'getInvoiceTypes',
        'has_attachment' => 'getHasAttachment'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('subject_type', $data ?? [], null);
        $this->setIfExists('date_range', $data ?? [], null);
        $this->setIfExists('ksef_number', $data ?? [], null);
        $this->setIfExists('invoice_number', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('seller_nip', $data ?? [], null);
        $this->setIfExists('buyer_identifier', $data ?? [], null);
        $this->setIfExists('currency_codes', $data ?? [], null);
        $this->setIfExists('invoicing_mode', $data ?? [], null);
        $this->setIfExists('is_self_invoicing', $data ?? [], null);
        $this->setIfExists('form_type', $data ?? [], null);
        $this->setIfExists('invoice_types', $data ?? [], null);
        $this->setIfExists('has_attachment', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['subject_type'] === null) {
            $invalidProperties[] = "'subject_type' can't be null";
        }
        if ($this->container['date_range'] === null) {
            $invalidProperties[] = "'date_range' can't be null";
        }
        if (!is_null($this->container['ksef_number']) && (mb_strlen($this->container['ksef_number']) > 36)) {
            $invalidProperties[] = "invalid value for 'ksef_number', the character length must be smaller than or equal to 36.";
        }

        if (!is_null($this->container['ksef_number']) && (mb_strlen($this->container['ksef_number']) < 35)) {
            $invalidProperties[] = "invalid value for 'ksef_number', the character length must be bigger than or equal to 35.";
        }

        if (!is_null($this->container['ksef_number']) && !preg_match("/^([1-9](\\d[1-9]|[1-9]\\d)\\d{7})-(20[2-9][0-9]|2[1-9]\\d{2}|[3-9]\\d{3})(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])-([0-9A-F]{6})-?([0-9A-F]{6})-([0-9A-F]{2})$/", $this->container['ksef_number'])) {
            $invalidProperties[] = "invalid value for 'ksef_number', must be conform to the pattern /^([1-9](\\d[1-9]|[1-9]\\d)\\d{7})-(20[2-9][0-9]|2[1-9]\\d{2}|[3-9]\\d{3})(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])-([0-9A-F]{6})-?([0-9A-F]{6})-([0-9A-F]{2})$/.";
        }

        if (!is_null($this->container['invoice_number']) && (mb_strlen($this->container['invoice_number']) > 256)) {
            $invalidProperties[] = "invalid value for 'invoice_number', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['seller_nip']) && (mb_strlen($this->container['seller_nip']) > 10)) {
            $invalidProperties[] = "invalid value for 'seller_nip', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['seller_nip']) && (mb_strlen($this->container['seller_nip']) < 10)) {
            $invalidProperties[] = "invalid value for 'seller_nip', the character length must be bigger than or equal to 10.";
        }

        if (!is_null($this->container['seller_nip']) && !preg_match("/^[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}$/", $this->container['seller_nip'])) {
            $invalidProperties[] = "invalid value for 'seller_nip', must be conform to the pattern /^[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets subject_type
     *
     * @return \NetSeven\KseF2Model\InvoiceQuerySubjectType
     */
    public function getSubjectType(): \NetSeven\KseF2Model\InvoiceQuerySubjectType
    {
        return $this->container['subject_type'];
    }

    /**
     * Sets subject_type
     *
     * @param \NetSeven\KseF2Model\InvoiceQuerySubjectType $subject_type Typ podmiotu, którego dotyczą kryteria filtrowania metadanych faktur. Określa kontekst, w jakim przeszukiwane są dane. | Wartość | Opis | | --- | --- | | Subject1 | Podmiot 1 - sprzedawca | | Subject2 | Podmiot 2 - nabywca | | Subject3 | Podmiot 3 | | SubjectAuthorized | Podmiot upoważniony |
     *
     * @return $this
     */
    public function setSubjectType(\NetSeven\KseF2Model\InvoiceQuerySubjectType $subject_type): static
    {
        if (is_null($subject_type)) {
            throw new InvalidArgumentException('non-nullable subject_type cannot be null');
        }
        $this->container['subject_type'] = $subject_type;

        return $this;
    }

    /**
     * Gets date_range
     *
     * @return \NetSeven\KseF2Model\InvoiceQueryDateRange
     */
    public function getDateRange(): \NetSeven\KseF2Model\InvoiceQueryDateRange
    {
        return $this->container['date_range'];
    }

    /**
     * Sets date_range
     *
     * @param \NetSeven\KseF2Model\InvoiceQueryDateRange $date_range Typ i zakres dat, według którego mają być filtrowane faktury. Dozwolony maksymalny okres wynosi 2 lata.
     *
     * @return $this
     */
    public function setDateRange(\NetSeven\KseF2Model\InvoiceQueryDateRange $date_range): static
    {
        if (is_null($date_range)) {
            throw new InvalidArgumentException('non-nullable date_range cannot be null');
        }
        $this->container['date_range'] = $date_range;

        return $this;
    }

    /**
     * Gets ksef_number
     *
     * @return string|null
     */
    public function getKsefNumber(): ?string
    {
        return $this->container['ksef_number'];
    }

    /**
     * Sets ksef_number
     *
     * @param string|null $ksef_number Numer KSeF faktury (exact match).
     *
     * @return $this
     */
    public function setKsefNumber(?string $ksef_number): static
    {
        if (is_null($ksef_number)) {
            array_push($this->openAPINullablesSetToNull, 'ksef_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ksef_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($ksef_number) && (mb_strlen($ksef_number) > 36)) {
            throw new InvalidArgumentException('invalid length for $ksef_number when calling InvoiceQueryFilters., must be smaller than or equal to 36.');
        }
        if (!is_null($ksef_number) && (mb_strlen($ksef_number) < 35)) {
            throw new InvalidArgumentException('invalid length for $ksef_number when calling InvoiceQueryFilters., must be bigger than or equal to 35.');
        }
        if (!is_null($ksef_number) && (!preg_match("/^([1-9](\\d[1-9]|[1-9]\\d)\\d{7})-(20[2-9][0-9]|2[1-9]\\d{2}|[3-9]\\d{3})(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])-([0-9A-F]{6})-?([0-9A-F]{6})-([0-9A-F]{2})$/", ObjectSerializer::toString($ksef_number)))) {
            throw new InvalidArgumentException("invalid value for \$ksef_number when calling InvoiceQueryFilters., must conform to the pattern /^([1-9](\\d[1-9]|[1-9]\\d)\\d{7})-(20[2-9][0-9]|2[1-9]\\d{2}|[3-9]\\d{3})(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])-([0-9A-F]{6})-?([0-9A-F]{6})-([0-9A-F]{2})$/.");
        }

        $this->container['ksef_number'] = $ksef_number;

        return $this;
    }

    /**
     * Gets invoice_number
     *
     * @return string|null
     */
    public function getInvoiceNumber(): ?string
    {
        return $this->container['invoice_number'];
    }

    /**
     * Sets invoice_number
     *
     * @param string|null $invoice_number Numer faktury nadany przez wystawcę (exact match).
     *
     * @return $this
     */
    public function setInvoiceNumber(?string $invoice_number): static
    {
        if (is_null($invoice_number)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($invoice_number) && (mb_strlen($invoice_number) > 256)) {
            throw new InvalidArgumentException('invalid length for $invoice_number when calling InvoiceQueryFilters., must be smaller than or equal to 256.');
        }

        $this->container['invoice_number'] = $invoice_number;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return \NetSeven\KseF2Model\InvoiceQueryAmount|null
     */
    public function getAmount(): ?\NetSeven\KseF2Model\InvoiceQueryAmount
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param \NetSeven\KseF2Model\InvoiceQueryAmount|null $amount Filtr kwotowy – brutto, netto lub VAT (z wartością).
     *
     * @return $this
     */
    public function setAmount(?\NetSeven\KseF2Model\InvoiceQueryAmount $amount): static
    {
        if (is_null($amount)) {
            array_push($this->openAPINullablesSetToNull, 'amount');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('amount', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets seller_nip
     *
     * @return string|null
     */
    public function getSellerNip(): ?string
    {
        return $this->container['seller_nip'];
    }

    /**
     * Sets seller_nip
     *
     * @param string|null $seller_nip Nip sprzedawcy (exact match).
     *
     * @return $this
     */
    public function setSellerNip(?string $seller_nip): static
    {
        if (is_null($seller_nip)) {
            array_push($this->openAPINullablesSetToNull, 'seller_nip');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('seller_nip', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($seller_nip) && (mb_strlen($seller_nip) > 10)) {
            throw new InvalidArgumentException('invalid length for $seller_nip when calling InvoiceQueryFilters., must be smaller than or equal to 10.');
        }
        if (!is_null($seller_nip) && (mb_strlen($seller_nip) < 10)) {
            throw new InvalidArgumentException('invalid length for $seller_nip when calling InvoiceQueryFilters., must be bigger than or equal to 10.');
        }
        if (!is_null($seller_nip) && (!preg_match("/^[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}$/", ObjectSerializer::toString($seller_nip)))) {
            throw new InvalidArgumentException("invalid value for \$seller_nip when calling InvoiceQueryFilters., must conform to the pattern /^[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}$/.");
        }

        $this->container['seller_nip'] = $seller_nip;

        return $this;
    }

    /**
     * Gets buyer_identifier
     *
     * @return \NetSeven\KseF2Model\InvoiceQueryBuyerIdentifier|null
     */
    public function getBuyerIdentifier(): ?\NetSeven\KseF2Model\InvoiceQueryBuyerIdentifier
    {
        return $this->container['buyer_identifier'];
    }

    /**
     * Sets buyer_identifier
     *
     * @param \NetSeven\KseF2Model\InvoiceQueryBuyerIdentifier|null $buyer_identifier Identyfikator nabywcy. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | VatUe | Identyfikator VAT UE podmiotu unijnego. | | Other | Inny identyfikator| | None  | Brak identyfikatora nabywcy |
     *
     * @return $this
     */
    public function setBuyerIdentifier(?\NetSeven\KseF2Model\InvoiceQueryBuyerIdentifier $buyer_identifier): static
    {
        if (is_null($buyer_identifier)) {
            array_push($this->openAPINullablesSetToNull, 'buyer_identifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('buyer_identifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['buyer_identifier'] = $buyer_identifier;

        return $this;
    }

    /**
     * Gets currency_codes
     *
     * @return \NetSeven\KseF2Model\CurrencyCode[]|null
     */
    public function getCurrencyCodes(): ?array
    {
        return $this->container['currency_codes'];
    }

    /**
     * Sets currency_codes
     *
     * @param \NetSeven\KseF2Model\CurrencyCode[]|null $currency_codes Kody walut.
     *
     * @return $this
     */
    public function setCurrencyCodes(?array $currency_codes): static
    {
        if (is_null($currency_codes)) {
            array_push($this->openAPINullablesSetToNull, 'currency_codes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('currency_codes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['currency_codes'] = $currency_codes;

        return $this;
    }

    /**
     * Gets invoicing_mode
     *
     * @return \NetSeven\KseF2Model\InvoicingMode|null
     */
    public function getInvoicingMode(): ?\NetSeven\KseF2Model\InvoicingMode
    {
        return $this->container['invoicing_mode'];
    }

    /**
     * Sets invoicing_mode
     *
     * @param \NetSeven\KseF2Model\InvoicingMode|null $invoicing_mode Tryb wystawienia faktury: online lub offline.
     *
     * @return $this
     */
    public function setInvoicingMode(?\NetSeven\KseF2Model\InvoicingMode $invoicing_mode): static
    {
        if (is_null($invoicing_mode)) {
            array_push($this->openAPINullablesSetToNull, 'invoicing_mode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoicing_mode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoicing_mode'] = $invoicing_mode;

        return $this;
    }

    /**
     * Gets is_self_invoicing
     *
     * @return bool|null
     */
    public function getIsSelfInvoicing(): ?bool
    {
        return $this->container['is_self_invoicing'];
    }

    /**
     * Sets is_self_invoicing
     *
     * @param bool|null $is_self_invoicing Czy faktura została wystawiona w trybie samofakturowania.
     *
     * @return $this
     */
    public function setIsSelfInvoicing(?bool $is_self_invoicing): static
    {
        if (is_null($is_self_invoicing)) {
            array_push($this->openAPINullablesSetToNull, 'is_self_invoicing');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_self_invoicing', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_self_invoicing'] = $is_self_invoicing;

        return $this;
    }

    /**
     * Gets form_type
     *
     * @return \NetSeven\KseF2Model\InvoiceQueryFormType|null
     */
    public function getFormType(): ?\NetSeven\KseF2Model\InvoiceQueryFormType
    {
        return $this->container['form_type'];
    }

    /**
     * Sets form_type
     *
     * @param \NetSeven\KseF2Model\InvoiceQueryFormType|null $form_type Typ dokumentu. | Wartość | Opis | | --- | --- | | FA | Faktura VAT | | PEF | Faktura PEF | | RR | Faktura RR |
     *
     * @return $this
     */
    public function setFormType(?\NetSeven\KseF2Model\InvoiceQueryFormType $form_type): static
    {
        if (is_null($form_type)) {
            array_push($this->openAPINullablesSetToNull, 'form_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('form_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['form_type'] = $form_type;

        return $this;
    }

    /**
     * Gets invoice_types
     *
     * @return \NetSeven\KseF2Model\InvoiceType[]|null
     */
    public function getInvoiceTypes(): ?array
    {
        return $this->container['invoice_types'];
    }

    /**
     * Sets invoice_types
     *
     * @param \NetSeven\KseF2Model\InvoiceType[]|null $invoice_types Rodzaje faktur. | Wartość | Opis | | --- | --- | | Vat | (FA) Podstawowa | | Zal | (FA) Zaliczkowa | | Kor | (FA) Korygująca | | Roz | (FA) Rozliczeniowa | | Upr | (FA) Uproszczona | | KorZal | (FA) Korygująca fakturę zaliczkową | | KorRoz | (FA) Korygująca fakturę rozliczeniową | | VatPef | (PEF) Podstawowowa | | VatPefSp | (PEF) Specjalizowana | | KorPef | (PEF) Korygująca | | VatRr | (RR) Podstawowa | | KorVatRr | (RR) Korygująca |
     *
     * @return $this
     */
    public function setInvoiceTypes(?array $invoice_types): static
    {
        if (is_null($invoice_types)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_types');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_types', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_types'] = $invoice_types;

        return $this;
    }

    /**
     * Gets has_attachment
     *
     * @return bool|null
     */
    public function getHasAttachment(): ?bool
    {
        return $this->container['has_attachment'];
    }

    /**
     * Sets has_attachment
     *
     * @param bool|null $has_attachment Czy faktura ma załącznik.
     *
     * @return $this
     */
    public function setHasAttachment(?bool $has_attachment): static
    {
        if (is_null($has_attachment)) {
            array_push($this->openAPINullablesSetToNull, 'has_attachment');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('has_attachment', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['has_attachment'] = $has_attachment;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


