<?php
/**
 * PersonalPermission
 *
 * PHP version 8.1
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API TE
 *
 * **Wersja API:** 2.0.0 (build 2.0.0-rc5.7-te-20251115.1+12de7e512c6dede0af882fee4f7e52fc04590ab4)<br> **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br> **Historia zmian:** [Changelog](https://github.com/CIRFMF/ksef-docs/blob/main/api-changelog.md)<br> **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 * The version of the OpenAPI document: v2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NetSeven\KseF2Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use NetSeven\ObjectSerializer;

/**
 * PersonalPermission Class Doc Comment
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class PersonalPermission implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'PersonalPermission';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'string',
        'context_identifier' => '\NetSeven\KseF2Model\PersonalPermissionsContextIdentifier',
        'authorized_identifier' => '\NetSeven\KseF2Model\PersonalPermissionsAuthorizedIdentifier',
        'target_identifier' => '\NetSeven\KseF2Model\PersonalPermissionsTargetIdentifier',
        'permission_scope' => '\NetSeven\KseF2Model\PersonalPermissionScope',
        'description' => 'string',
        'permission_state' => '\NetSeven\KseF2Model\PermissionState',
        'start_date' => '\DateTime',
        'can_delegate' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => null,
        'context_identifier' => null,
        'authorized_identifier' => null,
        'target_identifier' => null,
        'permission_scope' => null,
        'description' => null,
        'permission_state' => null,
        'start_date' => 'date-time',
        'can_delegate' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => false,
        'context_identifier' => true,
        'authorized_identifier' => true,
        'target_identifier' => true,
        'permission_scope' => false,
        'description' => false,
        'permission_state' => false,
        'start_date' => false,
        'can_delegate' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'context_identifier' => 'contextIdentifier',
        'authorized_identifier' => 'authorizedIdentifier',
        'target_identifier' => 'targetIdentifier',
        'permission_scope' => 'permissionScope',
        'description' => 'description',
        'permission_state' => 'permissionState',
        'start_date' => 'startDate',
        'can_delegate' => 'canDelegate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'context_identifier' => 'setContextIdentifier',
        'authorized_identifier' => 'setAuthorizedIdentifier',
        'target_identifier' => 'setTargetIdentifier',
        'permission_scope' => 'setPermissionScope',
        'description' => 'setDescription',
        'permission_state' => 'setPermissionState',
        'start_date' => 'setStartDate',
        'can_delegate' => 'setCanDelegate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'context_identifier' => 'getContextIdentifier',
        'authorized_identifier' => 'getAuthorizedIdentifier',
        'target_identifier' => 'getTargetIdentifier',
        'permission_scope' => 'getPermissionScope',
        'description' => 'getDescription',
        'permission_state' => 'getPermissionState',
        'start_date' => 'getStartDate',
        'can_delegate' => 'getCanDelegate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('context_identifier', $data ?? [], null);
        $this->setIfExists('authorized_identifier', $data ?? [], null);
        $this->setIfExists('target_identifier', $data ?? [], null);
        $this->setIfExists('permission_scope', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('permission_state', $data ?? [], null);
        $this->setIfExists('start_date', $data ?? [], null);
        $this->setIfExists('can_delegate', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ((mb_strlen($this->container['id']) > 36)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be smaller than or equal to 36.";
        }

        if ((mb_strlen($this->container['id']) < 36)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be bigger than or equal to 36.";
        }

        if ($this->container['permission_scope'] === null) {
            $invalidProperties[] = "'permission_scope' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ((mb_strlen($this->container['description']) > 256)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 256.";
        }

        if ((mb_strlen($this->container['description']) < 5)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be bigger than or equal to 5.";
        }

        if ($this->container['permission_state'] === null) {
            $invalidProperties[] = "'permission_state' can't be null";
        }
        if ($this->container['start_date'] === null) {
            $invalidProperties[] = "'start_date' can't be null";
        }
        if ($this->container['can_delegate'] === null) {
            $invalidProperties[] = "'can_delegate' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Identyfikator uprawnienia.
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        if ((mb_strlen($id) > 36)) {
            throw new InvalidArgumentException('invalid length for $id when calling PersonalPermission., must be smaller than or equal to 36.');
        }
        if ((mb_strlen($id) < 36)) {
            throw new InvalidArgumentException('invalid length for $id when calling PersonalPermission., must be bigger than or equal to 36.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets context_identifier
     *
     * @return \NetSeven\KseF2Model\PersonalPermissionsContextIdentifier|null
     */
    public function getContextIdentifier(): ?\NetSeven\KseF2Model\PersonalPermissionsContextIdentifier
    {
        return $this->container['context_identifier'];
    }

    /**
     * Sets context_identifier
     *
     * @param \NetSeven\KseF2Model\PersonalPermissionsContextIdentifier|null $context_identifier Identyfikator kontekstu podmiotu, który nadał uprawnienia do obsługi faktur. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP |
     *
     * @return $this
     */
    public function setContextIdentifier(?\NetSeven\KseF2Model\PersonalPermissionsContextIdentifier $context_identifier): static
    {
        if (is_null($context_identifier)) {
            array_push($this->openAPINullablesSetToNull, 'context_identifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('context_identifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['context_identifier'] = $context_identifier;

        return $this;
    }

    /**
     * Gets authorized_identifier
     *
     * @return \NetSeven\KseF2Model\PersonalPermissionsAuthorizedIdentifier|null
     */
    public function getAuthorizedIdentifier(): ?\NetSeven\KseF2Model\PersonalPermissionsAuthorizedIdentifier
    {
        return $this->container['authorized_identifier'];
    }

    /**
     * Sets authorized_identifier
     *
     * @param \NetSeven\KseF2Model\PersonalPermissionsAuthorizedIdentifier|null $authorized_identifier Identyfikator podmiotu uprawnionego, jeżeli jest inny niż identyfikator uwierzytelnionego klienta API. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP |
     *
     * @return $this
     */
    public function setAuthorizedIdentifier(?\NetSeven\KseF2Model\PersonalPermissionsAuthorizedIdentifier $authorized_identifier): static
    {
        if (is_null($authorized_identifier)) {
            array_push($this->openAPINullablesSetToNull, 'authorized_identifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorized_identifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorized_identifier'] = $authorized_identifier;

        return $this;
    }

    /**
     * Gets target_identifier
     *
     * @return \NetSeven\KseF2Model\PersonalPermissionsTargetIdentifier|null
     */
    public function getTargetIdentifier(): ?\NetSeven\KseF2Model\PersonalPermissionsTargetIdentifier
    {
        return $this->container['target_identifier'];
    }

    /**
     * Sets target_identifier
     *
     * @param \NetSeven\KseF2Model\PersonalPermissionsTargetIdentifier|null $target_identifier Identyfikator podmiotu docelowego dla uprawnień selektywnych nadanych pośrednio. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | AllPartners | Identyfikator oznaczający, że wyszukiwanie dotyczy uprawnień generalnych nadanych w sposób pośredni | | InternalId | Dwuczłonowy identyfikator składający się z numeru NIP i 5 cyfr: `{nip}-{5_cyfr}` |
     *
     * @return $this
     */
    public function setTargetIdentifier(?\NetSeven\KseF2Model\PersonalPermissionsTargetIdentifier $target_identifier): static
    {
        if (is_null($target_identifier)) {
            array_push($this->openAPINullablesSetToNull, 'target_identifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('target_identifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['target_identifier'] = $target_identifier;

        return $this;
    }

    /**
     * Gets permission_scope
     *
     * @return \NetSeven\KseF2Model\PersonalPermissionScope
     */
    public function getPermissionScope(): \NetSeven\KseF2Model\PersonalPermissionScope
    {
        return $this->container['permission_scope'];
    }

    /**
     * Sets permission_scope
     *
     * @param \NetSeven\KseF2Model\PersonalPermissionScope $permission_scope Rodzaj uprawnienia.
     *
     * @return $this
     */
    public function setPermissionScope(\NetSeven\KseF2Model\PersonalPermissionScope $permission_scope): static
    {
        if (is_null($permission_scope)) {
            throw new InvalidArgumentException('non-nullable permission_scope cannot be null');
        }
        $this->container['permission_scope'] = $permission_scope;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription(): string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description Opis uprawnienia.
     *
     * @return $this
     */
    public function setDescription(string $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 256)) {
            throw new InvalidArgumentException('invalid length for $description when calling PersonalPermission., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($description) < 5)) {
            throw new InvalidArgumentException('invalid length for $description when calling PersonalPermission., must be bigger than or equal to 5.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets permission_state
     *
     * @return \NetSeven\KseF2Model\PermissionState
     */
    public function getPermissionState(): \NetSeven\KseF2Model\PermissionState
    {
        return $this->container['permission_state'];
    }

    /**
     * Sets permission_state
     *
     * @param \NetSeven\KseF2Model\PermissionState $permission_state Stan uprawnienia.
     *
     * @return $this
     */
    public function setPermissionState(\NetSeven\KseF2Model\PermissionState $permission_state): static
    {
        if (is_null($permission_state)) {
            throw new InvalidArgumentException('non-nullable permission_state cannot be null');
        }
        $this->container['permission_state'] = $permission_state;

        return $this;
    }

    /**
     * Gets start_date
     *
     * @return \DateTime
     */
    public function getStartDate(): \DateTime
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     *
     * @param \DateTime $start_date Data rozpoczęcia obowiązywania uprawnienia.
     *
     * @return $this
     */
    public function setStartDate(\DateTime $start_date): static
    {
        if (is_null($start_date)) {
            throw new InvalidArgumentException('non-nullable start_date cannot be null');
        }
        $this->container['start_date'] = $start_date;

        return $this;
    }

    /**
     * Gets can_delegate
     *
     * @return bool
     */
    public function getCanDelegate(): bool
    {
        return $this->container['can_delegate'];
    }

    /**
     * Sets can_delegate
     *
     * @param bool $can_delegate Flaga określająca, czy uprawnienie ma być możliwe do dalszego przekazywania.
     *
     * @return $this
     */
    public function setCanDelegate(bool $can_delegate): static
    {
        if (is_null($can_delegate)) {
            throw new InvalidArgumentException('non-nullable can_delegate cannot be null');
        }
        $this->container['can_delegate'] = $can_delegate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


