<?php
/**
 * PersonalPermissionType
 *
 * PHP version 8.1
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API TE
 *
 * **Wersja API:** 2.0.0 (build 2.0.0-rc5.7-te-20251115.1+12de7e512c6dede0af882fee4f7e52fc04590ab4)<br> **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br> **Historia zmian:** [Changelog](https://github.com/CIRFMF/ksef-docs/blob/main/api-changelog.md)<br> **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 * The version of the OpenAPI document: v2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NetSeven\KseF2Model;

/**
 * PersonalPermissionType Class Doc Comment
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum PersonalPermissionType: string
{
    case CREDENTIALS_MANAGE = 'CredentialsManage';

    case CREDENTIALS_READ = 'CredentialsRead';

    case INVOICE_WRITE = 'InvoiceWrite';

    case INVOICE_READ = 'InvoiceRead';

    case INTROSPECTION = 'Introspection';

    case SUBUNIT_MANAGE = 'SubunitManage';

    case ENFORCEMENT_OPERATIONS = 'EnforcementOperations';

    case VAT_UE_MANAGE = 'VatUeManage';
}


