<?php
/**
 * ThirdSubjectIdentifierType
 *
 * PHP version 8.1
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API TE
 *
 * **Wersja API:** 2.0.0 (build 2.0.0-rc5.7-te-20251115.1+12de7e512c6dede0af882fee4f7e52fc04590ab4)<br> **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br> **Historia zmian:** [Changelog](https://github.com/CIRFMF/ksef-docs/blob/main/api-changelog.md)<br> **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 * The version of the OpenAPI document: v2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NetSeven\KseF2Model;

/**
 * ThirdSubjectIdentifierType Class Doc Comment
 *
 * @description | Wartość | Opis | | --- | --- | | Nip | 10 cyfrowy numer NIP | | InternalId | Identyfikator wewnętrzny, składający się z numeru NIP i 5 cyfr. | | VatUe | Identyfikator VAT UE podmiotu unijnego | | Other | Inny identyfikator | | None | Brak identyfikatora podmiotu trzeciego |
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ThirdSubjectIdentifierType: string
{
    case NIP = 'Nip';

    case INTERNAL_ID = 'InternalId';

    case VAT_UE = 'VatUe';

    case OTHER = 'Other';

    case NONE = 'None';
}


