<?php
/**
 * CertyfikatyApiTest
 * PHP version 8.1
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API TE
 *
 * **Wersja API:** 2.0.0 (build 2.0.0-rc5.7-te-20251115.1+12de7e512c6dede0af882fee4f7e52fc04590ab4)<br> **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br> **Historia zmian:** [Changelog](https://github.com/CIRFMF/ksef-docs/blob/main/api-changelog.md)<br> **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 * The version of the OpenAPI document: v2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace NetSeven\Test\Api;

use NetSeven\Configuration;
use NetSeven\ApiException;
use NetSeven\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CertyfikatyApiTest Class Doc Comment
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CertyfikatyApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2CertificatesCertificateSerialNumberRevokePost
     *
     * Unieważnienie certyfikatu.
     *
     */
    public function testApiV2CertificatesCertificateSerialNumberRevokePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2CertificatesEnrollmentsDataGet
     *
     * Pobranie danych do wniosku certyfikacyjnego.
     *
     */
    public function testApiV2CertificatesEnrollmentsDataGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2CertificatesEnrollmentsPost
     *
     * Wysyłka wniosku certyfikacyjnego.
     *
     */
    public function testApiV2CertificatesEnrollmentsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2CertificatesEnrollmentsReferenceNumberGet
     *
     * Pobranie statusu przetwarzania wniosku certyfikacyjnego.
     *
     */
    public function testApiV2CertificatesEnrollmentsReferenceNumberGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2CertificatesLimitsGet
     *
     * Pobranie danych o limitach certyfikatów.
     *
     */
    public function testApiV2CertificatesLimitsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2CertificatesQueryPost
     *
     * Pobranie listy metadanych certyfikatów.
     *
     */
    public function testApiV2CertificatesQueryPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2CertificatesRetrievePost
     *
     * Pobranie certyfikatu lub listy certyfikatów.
     *
     */
    public function testApiV2CertificatesRetrievePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
