<?php
/**
 * NadawanieUprawnieApiTest
 * PHP version 8.1
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API TE
 *
 * **Wersja API:** 2.0.0 (build 2.0.0-rc5.7-te-20251115.1+12de7e512c6dede0af882fee4f7e52fc04590ab4)<br> **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br> **Historia zmian:** [Changelog](https://github.com/CIRFMF/ksef-docs/blob/main/api-changelog.md)<br> **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 * The version of the OpenAPI document: v2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace NetSeven\Test\Api;

use NetSeven\Configuration;
use NetSeven\ApiException;
use NetSeven\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * NadawanieUprawnieApiTest Class Doc Comment
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NadawanieUprawnieApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2PermissionsAuthorizationsGrantsPost
     *
     * Nadanie uprawnień podmiotowych.
     *
     */
    public function testApiV2PermissionsAuthorizationsGrantsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2PermissionsEntitiesGrantsPost
     *
     * Nadanie podmiotom uprawnień do obsługi faktur.
     *
     */
    public function testApiV2PermissionsEntitiesGrantsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2PermissionsEuEntitiesAdministrationGrantsPost
     *
     * Nadanie uprawnień administratora podmiotu unijnego.
     *
     */
    public function testApiV2PermissionsEuEntitiesAdministrationGrantsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2PermissionsEuEntitiesGrantsPost
     *
     * Nadanie uprawnień reprezentanta podmiotu unijnego.
     *
     */
    public function testApiV2PermissionsEuEntitiesGrantsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2PermissionsIndirectGrantsPost
     *
     * Nadanie uprawnień w sposób pośredni.
     *
     */
    public function testApiV2PermissionsIndirectGrantsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2PermissionsPersonsGrantsPost
     *
     * Nadanie osobom fizycznym uprawnień do pracy w KSeF.
     *
     */
    public function testApiV2PermissionsPersonsGrantsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2PermissionsSubunitsGrantsPost
     *
     * Nadanie uprawnień administratora podmiotu podrzędnego.
     *
     */
    public function testApiV2PermissionsSubunitsGrantsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
