<?php
/**
 * OdbieranieUprawnieApi
 * PHP version 8.1
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API TE
 *
 * **Wersja API:** 2.0.0 (build 2.0.0-rc5.7-te-20251115.1+12de7e512c6dede0af882fee4f7e52fc04590ab4)<br> **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br> **Historia zmian:** [Changelog](https://github.com/CIRFMF/ksef-docs/blob/main/api-changelog.md)<br> **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 * The version of the OpenAPI document: v2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NetSeven\KseF2Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use NetSeven\ApiException;
use NetSeven\Configuration;
use NetSeven\HeaderSelector;
use NetSeven\FormDataProcessor;
use NetSeven\ObjectSerializer;

/**
 * OdbieranieUprawnieApi Class Doc Comment
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OdbieranieUprawnieApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV2PermissionsAuthorizationsGrantsPermissionIdDelete' => [
            'application/json',
        ],
        'apiV2PermissionsCommonGrantsPermissionIdDelete' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation apiV2PermissionsAuthorizationsGrantsPermissionIdDelete
     *
     * Odebranie uprawnień podmiotowych
     *
     * @param  string $permission_id Id uprawnienia. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsAuthorizationsGrantsPermissionIdDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \NetSeven\KseF2Model\PermissionsOperationResponse|\NetSeven\KseF2Model\ExceptionResponse
     */
    public function apiV2PermissionsAuthorizationsGrantsPermissionIdDelete(
        string $permission_id,
        string $contentType = self::contentTypes['apiV2PermissionsAuthorizationsGrantsPermissionIdDelete'][0]
    ): \NetSeven\KseF2Model\PermissionsOperationResponse|\NetSeven\KseF2Model\ExceptionResponse
    {
        list($response) = $this->apiV2PermissionsAuthorizationsGrantsPermissionIdDeleteWithHttpInfo($permission_id, $contentType);
        return $response;
    }

    /**
     * Operation apiV2PermissionsAuthorizationsGrantsPermissionIdDeleteWithHttpInfo
     *
     * Odebranie uprawnień podmiotowych
     *
     * @param  string $permission_id Id uprawnienia. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsAuthorizationsGrantsPermissionIdDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \NetSeven\KseF2Model\PermissionsOperationResponse|\NetSeven\KseF2Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2PermissionsAuthorizationsGrantsPermissionIdDeleteWithHttpInfo(
        string $permission_id,
        string $contentType = self::contentTypes['apiV2PermissionsAuthorizationsGrantsPermissionIdDelete'][0]
    ): array
    {
        $request = $this->apiV2PermissionsAuthorizationsGrantsPermissionIdDeleteRequest($permission_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\PermissionsOperationResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NetSeven\KseF2Model\PermissionsOperationResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\PermissionsOperationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation apiV2PermissionsAuthorizationsGrantsPermissionIdDeleteAsync
     *
     * Odebranie uprawnień podmiotowych
     *
     * @param  string $permission_id Id uprawnienia. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsAuthorizationsGrantsPermissionIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2PermissionsAuthorizationsGrantsPermissionIdDeleteAsync(
        string $permission_id,
        string $contentType = self::contentTypes['apiV2PermissionsAuthorizationsGrantsPermissionIdDelete'][0]
    ): PromiseInterface
    {
        return $this->apiV2PermissionsAuthorizationsGrantsPermissionIdDeleteAsyncWithHttpInfo($permission_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2PermissionsAuthorizationsGrantsPermissionIdDeleteAsyncWithHttpInfo
     *
     * Odebranie uprawnień podmiotowych
     *
     * @param  string $permission_id Id uprawnienia. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsAuthorizationsGrantsPermissionIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2PermissionsAuthorizationsGrantsPermissionIdDeleteAsyncWithHttpInfo(
        string $permission_id,
        string $contentType = self::contentTypes['apiV2PermissionsAuthorizationsGrantsPermissionIdDelete'][0]
    ): PromiseInterface
    {
        $returnType = '\NetSeven\KseF2Model\PermissionsOperationResponse';
        $request = $this->apiV2PermissionsAuthorizationsGrantsPermissionIdDeleteRequest($permission_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2PermissionsAuthorizationsGrantsPermissionIdDelete'
     *
     * @param  string $permission_id Id uprawnienia. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsAuthorizationsGrantsPermissionIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2PermissionsAuthorizationsGrantsPermissionIdDeleteRequest(
        string $permission_id,
        string $contentType = self::contentTypes['apiV2PermissionsAuthorizationsGrantsPermissionIdDelete'][0]
    ): Request
    {

        // verify the required parameter 'permission_id' is set
        if ($permission_id === null || (is_array($permission_id) && count($permission_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $permission_id when calling apiV2PermissionsAuthorizationsGrantsPermissionIdDelete'
            );
        }
        if (strlen($permission_id) > 36) {
            throw new InvalidArgumentException('invalid length for "$permission_id" when calling OdbieranieUprawnieApi.apiV2PermissionsAuthorizationsGrantsPermissionIdDelete, must be smaller than or equal to 36.');
        }
        if (strlen($permission_id) < 36) {
            throw new InvalidArgumentException('invalid length for "$permission_id" when calling OdbieranieUprawnieApi.apiV2PermissionsAuthorizationsGrantsPermissionIdDelete, must be bigger than or equal to 36.');
        }
        

        $resourcePath = '/api/v2/permissions/authorizations/grants/{permissionId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($permission_id !== null) {
            $resourcePath = str_replace(
                '{' . 'permissionId' . '}',
                ObjectSerializer::toPathValue($permission_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2PermissionsCommonGrantsPermissionIdDelete
     *
     * Odebranie uprawnień
     *
     * @param  string $permission_id Id uprawnienia. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsCommonGrantsPermissionIdDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \NetSeven\KseF2Model\PermissionsOperationResponse|\NetSeven\KseF2Model\ExceptionResponse
     */
    public function apiV2PermissionsCommonGrantsPermissionIdDelete(
        string $permission_id,
        string $contentType = self::contentTypes['apiV2PermissionsCommonGrantsPermissionIdDelete'][0]
    ): \NetSeven\KseF2Model\PermissionsOperationResponse|\NetSeven\KseF2Model\ExceptionResponse
    {
        list($response) = $this->apiV2PermissionsCommonGrantsPermissionIdDeleteWithHttpInfo($permission_id, $contentType);
        return $response;
    }

    /**
     * Operation apiV2PermissionsCommonGrantsPermissionIdDeleteWithHttpInfo
     *
     * Odebranie uprawnień
     *
     * @param  string $permission_id Id uprawnienia. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsCommonGrantsPermissionIdDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \NetSeven\KseF2Model\PermissionsOperationResponse|\NetSeven\KseF2Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2PermissionsCommonGrantsPermissionIdDeleteWithHttpInfo(
        string $permission_id,
        string $contentType = self::contentTypes['apiV2PermissionsCommonGrantsPermissionIdDelete'][0]
    ): array
    {
        $request = $this->apiV2PermissionsCommonGrantsPermissionIdDeleteRequest($permission_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\PermissionsOperationResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NetSeven\KseF2Model\PermissionsOperationResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\PermissionsOperationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation apiV2PermissionsCommonGrantsPermissionIdDeleteAsync
     *
     * Odebranie uprawnień
     *
     * @param  string $permission_id Id uprawnienia. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsCommonGrantsPermissionIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2PermissionsCommonGrantsPermissionIdDeleteAsync(
        string $permission_id,
        string $contentType = self::contentTypes['apiV2PermissionsCommonGrantsPermissionIdDelete'][0]
    ): PromiseInterface
    {
        return $this->apiV2PermissionsCommonGrantsPermissionIdDeleteAsyncWithHttpInfo($permission_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2PermissionsCommonGrantsPermissionIdDeleteAsyncWithHttpInfo
     *
     * Odebranie uprawnień
     *
     * @param  string $permission_id Id uprawnienia. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsCommonGrantsPermissionIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2PermissionsCommonGrantsPermissionIdDeleteAsyncWithHttpInfo(
        string $permission_id,
        string $contentType = self::contentTypes['apiV2PermissionsCommonGrantsPermissionIdDelete'][0]
    ): PromiseInterface
    {
        $returnType = '\NetSeven\KseF2Model\PermissionsOperationResponse';
        $request = $this->apiV2PermissionsCommonGrantsPermissionIdDeleteRequest($permission_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2PermissionsCommonGrantsPermissionIdDelete'
     *
     * @param  string $permission_id Id uprawnienia. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsCommonGrantsPermissionIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2PermissionsCommonGrantsPermissionIdDeleteRequest(
        string $permission_id,
        string $contentType = self::contentTypes['apiV2PermissionsCommonGrantsPermissionIdDelete'][0]
    ): Request
    {

        // verify the required parameter 'permission_id' is set
        if ($permission_id === null || (is_array($permission_id) && count($permission_id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $permission_id when calling apiV2PermissionsCommonGrantsPermissionIdDelete'
            );
        }
        if (strlen($permission_id) > 36) {
            throw new InvalidArgumentException('invalid length for "$permission_id" when calling OdbieranieUprawnieApi.apiV2PermissionsCommonGrantsPermissionIdDelete, must be smaller than or equal to 36.');
        }
        if (strlen($permission_id) < 36) {
            throw new InvalidArgumentException('invalid length for "$permission_id" when calling OdbieranieUprawnieApi.apiV2PermissionsCommonGrantsPermissionIdDelete, must be bigger than or equal to 36.');
        }
        

        $resourcePath = '/api/v2/permissions/common/grants/{permissionId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($permission_id !== null) {
            $resourcePath = str_replace(
                '{' . 'permissionId' . '}',
                ObjectSerializer::toPathValue($permission_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
