<?php
/**
 * UzyskiwanieDostpuApi
 * PHP version 8.1
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API TE
 *
 * **Wersja API:** 2.0.0 (build 2.0.0-rc5.7-te-20251115.1+12de7e512c6dede0af882fee4f7e52fc04590ab4)<br> **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br> **Historia zmian:** [Changelog](https://github.com/CIRFMF/ksef-docs/blob/main/api-changelog.md)<br> **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 * The version of the OpenAPI document: v2
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NetSeven\KseF2Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use NetSeven\ApiException;
use NetSeven\Configuration;
use NetSeven\HeaderSelector;
use NetSeven\FormDataProcessor;
use NetSeven\ObjectSerializer;

/**
 * UzyskiwanieDostpuApi Class Doc Comment
 *
 * @package  NetSeven
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UzyskiwanieDostpuApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV2AuthChallengePost' => [
            'application/json',
        ],
        'apiV2AuthKsefTokenPost' => [
            'application/json',
        ],
        'apiV2AuthReferenceNumberGet' => [
            'application/json',
        ],
        'apiV2AuthTokenRedeemPost' => [
            'application/json',
        ],
        'apiV2AuthTokenRefreshPost' => [
            'application/json',
        ],
        'apiV2AuthXadesSignaturePost' => [
            'application/xml',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation apiV2AuthChallengePost
     *
     * Inicjalizacja uwierzytelnienia
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthChallengePost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \NetSeven\KseF2Model\AuthenticationChallengeResponse|\NetSeven\KseF2Model\ExceptionResponse
     */
    public function apiV2AuthChallengePost(
        string $contentType = self::contentTypes['apiV2AuthChallengePost'][0]
    ): \NetSeven\KseF2Model\AuthenticationChallengeResponse|\NetSeven\KseF2Model\ExceptionResponse
    {
        list($response) = $this->apiV2AuthChallengePostWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation apiV2AuthChallengePostWithHttpInfo
     *
     * Inicjalizacja uwierzytelnienia
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthChallengePost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \NetSeven\KseF2Model\AuthenticationChallengeResponse|\NetSeven\KseF2Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2AuthChallengePostWithHttpInfo(
        string $contentType = self::contentTypes['apiV2AuthChallengePost'][0]
    ): array
    {
        $request = $this->apiV2AuthChallengePostRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\AuthenticationChallengeResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NetSeven\KseF2Model\AuthenticationChallengeResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\AuthenticationChallengeResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation apiV2AuthChallengePostAsync
     *
     * Inicjalizacja uwierzytelnienia
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthChallengePost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2AuthChallengePostAsync(
        string $contentType = self::contentTypes['apiV2AuthChallengePost'][0]
    ): PromiseInterface
    {
        return $this->apiV2AuthChallengePostAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2AuthChallengePostAsyncWithHttpInfo
     *
     * Inicjalizacja uwierzytelnienia
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthChallengePost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2AuthChallengePostAsyncWithHttpInfo(
        string $contentType = self::contentTypes['apiV2AuthChallengePost'][0]
    ): PromiseInterface
    {
        $returnType = '\NetSeven\KseF2Model\AuthenticationChallengeResponse';
        $request = $this->apiV2AuthChallengePostRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2AuthChallengePost'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthChallengePost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2AuthChallengePostRequest(
        string $contentType = self::contentTypes['apiV2AuthChallengePost'][0]
    ): Request
    {


        $resourcePath = '/api/v2/auth/challenge';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2AuthKsefTokenPost
     *
     * Uwierzytelnienie z wykorzystaniem tokena KSeF
     *
     * @param  \NetSeven\KseF2Model\InitTokenAuthenticationRequest|null $init_token_authentication_request init_token_authentication_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthKsefTokenPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \NetSeven\KseF2Model\AuthenticationInitResponse|\NetSeven\KseF2Model\ExceptionResponse
     */
    public function apiV2AuthKsefTokenPost(
        ?\NetSeven\KseF2Model\InitTokenAuthenticationRequest $init_token_authentication_request = null,
        string $contentType = self::contentTypes['apiV2AuthKsefTokenPost'][0]
    ): \NetSeven\KseF2Model\AuthenticationInitResponse|\NetSeven\KseF2Model\ExceptionResponse
    {
        list($response) = $this->apiV2AuthKsefTokenPostWithHttpInfo($init_token_authentication_request, $contentType);
        return $response;
    }

    /**
     * Operation apiV2AuthKsefTokenPostWithHttpInfo
     *
     * Uwierzytelnienie z wykorzystaniem tokena KSeF
     *
     * @param  \NetSeven\KseF2Model\InitTokenAuthenticationRequest|null $init_token_authentication_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthKsefTokenPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \NetSeven\KseF2Model\AuthenticationInitResponse|\NetSeven\KseF2Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2AuthKsefTokenPostWithHttpInfo(
        ?\NetSeven\KseF2Model\InitTokenAuthenticationRequest $init_token_authentication_request = null,
        string $contentType = self::contentTypes['apiV2AuthKsefTokenPost'][0]
    ): array
    {
        $request = $this->apiV2AuthKsefTokenPostRequest($init_token_authentication_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\AuthenticationInitResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NetSeven\KseF2Model\AuthenticationInitResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\AuthenticationInitResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation apiV2AuthKsefTokenPostAsync
     *
     * Uwierzytelnienie z wykorzystaniem tokena KSeF
     *
     * @param  \NetSeven\KseF2Model\InitTokenAuthenticationRequest|null $init_token_authentication_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthKsefTokenPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2AuthKsefTokenPostAsync(
        ?\NetSeven\KseF2Model\InitTokenAuthenticationRequest $init_token_authentication_request = null,
        string $contentType = self::contentTypes['apiV2AuthKsefTokenPost'][0]
    ): PromiseInterface
    {
        return $this->apiV2AuthKsefTokenPostAsyncWithHttpInfo($init_token_authentication_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2AuthKsefTokenPostAsyncWithHttpInfo
     *
     * Uwierzytelnienie z wykorzystaniem tokena KSeF
     *
     * @param  \NetSeven\KseF2Model\InitTokenAuthenticationRequest|null $init_token_authentication_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthKsefTokenPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2AuthKsefTokenPostAsyncWithHttpInfo(
        ?\NetSeven\KseF2Model\InitTokenAuthenticationRequest $init_token_authentication_request = null,
        string $contentType = self::contentTypes['apiV2AuthKsefTokenPost'][0]
    ): PromiseInterface
    {
        $returnType = '\NetSeven\KseF2Model\AuthenticationInitResponse';
        $request = $this->apiV2AuthKsefTokenPostRequest($init_token_authentication_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2AuthKsefTokenPost'
     *
     * @param  \NetSeven\KseF2Model\InitTokenAuthenticationRequest|null $init_token_authentication_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthKsefTokenPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2AuthKsefTokenPostRequest(
        ?\NetSeven\KseF2Model\InitTokenAuthenticationRequest $init_token_authentication_request = null,
        string $contentType = self::contentTypes['apiV2AuthKsefTokenPost'][0]
    ): Request
    {



        $resourcePath = '/api/v2/auth/ksef-token';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($init_token_authentication_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($init_token_authentication_request));
            } else {
                $httpBody = $init_token_authentication_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2AuthReferenceNumberGet
     *
     * Pobranie statusu uwierzytelniania
     *
     * @param  string $reference_number Numer referencyjny tokena otrzymanego przy inicjalizacji operacji uwierzytelniania. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthReferenceNumberGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \NetSeven\KseF2Model\AuthenticationOperationStatusResponse|\NetSeven\KseF2Model\ExceptionResponse
     */
    public function apiV2AuthReferenceNumberGet(
        string $reference_number,
        string $contentType = self::contentTypes['apiV2AuthReferenceNumberGet'][0]
    ): \NetSeven\KseF2Model\AuthenticationOperationStatusResponse|\NetSeven\KseF2Model\ExceptionResponse
    {
        list($response) = $this->apiV2AuthReferenceNumberGetWithHttpInfo($reference_number, $contentType);
        return $response;
    }

    /**
     * Operation apiV2AuthReferenceNumberGetWithHttpInfo
     *
     * Pobranie statusu uwierzytelniania
     *
     * @param  string $reference_number Numer referencyjny tokena otrzymanego przy inicjalizacji operacji uwierzytelniania. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthReferenceNumberGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \NetSeven\KseF2Model\AuthenticationOperationStatusResponse|\NetSeven\KseF2Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2AuthReferenceNumberGetWithHttpInfo(
        string $reference_number,
        string $contentType = self::contentTypes['apiV2AuthReferenceNumberGet'][0]
    ): array
    {
        $request = $this->apiV2AuthReferenceNumberGetRequest($reference_number, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\AuthenticationOperationStatusResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NetSeven\KseF2Model\AuthenticationOperationStatusResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\AuthenticationOperationStatusResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation apiV2AuthReferenceNumberGetAsync
     *
     * Pobranie statusu uwierzytelniania
     *
     * @param  string $reference_number Numer referencyjny tokena otrzymanego przy inicjalizacji operacji uwierzytelniania. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthReferenceNumberGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2AuthReferenceNumberGetAsync(
        string $reference_number,
        string $contentType = self::contentTypes['apiV2AuthReferenceNumberGet'][0]
    ): PromiseInterface
    {
        return $this->apiV2AuthReferenceNumberGetAsyncWithHttpInfo($reference_number, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2AuthReferenceNumberGetAsyncWithHttpInfo
     *
     * Pobranie statusu uwierzytelniania
     *
     * @param  string $reference_number Numer referencyjny tokena otrzymanego przy inicjalizacji operacji uwierzytelniania. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthReferenceNumberGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2AuthReferenceNumberGetAsyncWithHttpInfo(
        string $reference_number,
        string $contentType = self::contentTypes['apiV2AuthReferenceNumberGet'][0]
    ): PromiseInterface
    {
        $returnType = '\NetSeven\KseF2Model\AuthenticationOperationStatusResponse';
        $request = $this->apiV2AuthReferenceNumberGetRequest($reference_number, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2AuthReferenceNumberGet'
     *
     * @param  string $reference_number Numer referencyjny tokena otrzymanego przy inicjalizacji operacji uwierzytelniania. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthReferenceNumberGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2AuthReferenceNumberGetRequest(
        string $reference_number,
        string $contentType = self::contentTypes['apiV2AuthReferenceNumberGet'][0]
    ): Request
    {

        // verify the required parameter 'reference_number' is set
        if ($reference_number === null || (is_array($reference_number) && count($reference_number) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $reference_number when calling apiV2AuthReferenceNumberGet'
            );
        }
        if (strlen($reference_number) > 36) {
            throw new InvalidArgumentException('invalid length for "$reference_number" when calling UzyskiwanieDostpuApi.apiV2AuthReferenceNumberGet, must be smaller than or equal to 36.');
        }
        if (strlen($reference_number) < 36) {
            throw new InvalidArgumentException('invalid length for "$reference_number" when calling UzyskiwanieDostpuApi.apiV2AuthReferenceNumberGet, must be bigger than or equal to 36.');
        }
        

        $resourcePath = '/api/v2/auth/{referenceNumber}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($reference_number !== null) {
            $resourcePath = str_replace(
                '{' . 'referenceNumber' . '}',
                ObjectSerializer::toPathValue($reference_number),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2AuthTokenRedeemPost
     *
     * Pobranie tokenów dostępowych
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthTokenRedeemPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \NetSeven\KseF2Model\AuthenticationTokensResponse|\NetSeven\KseF2Model\ExceptionResponse
     */
    public function apiV2AuthTokenRedeemPost(
        string $contentType = self::contentTypes['apiV2AuthTokenRedeemPost'][0]
    ): \NetSeven\KseF2Model\AuthenticationTokensResponse|\NetSeven\KseF2Model\ExceptionResponse
    {
        list($response) = $this->apiV2AuthTokenRedeemPostWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation apiV2AuthTokenRedeemPostWithHttpInfo
     *
     * Pobranie tokenów dostępowych
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthTokenRedeemPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \NetSeven\KseF2Model\AuthenticationTokensResponse|\NetSeven\KseF2Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2AuthTokenRedeemPostWithHttpInfo(
        string $contentType = self::contentTypes['apiV2AuthTokenRedeemPost'][0]
    ): array
    {
        $request = $this->apiV2AuthTokenRedeemPostRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\AuthenticationTokensResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NetSeven\KseF2Model\AuthenticationTokensResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\AuthenticationTokensResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation apiV2AuthTokenRedeemPostAsync
     *
     * Pobranie tokenów dostępowych
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthTokenRedeemPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2AuthTokenRedeemPostAsync(
        string $contentType = self::contentTypes['apiV2AuthTokenRedeemPost'][0]
    ): PromiseInterface
    {
        return $this->apiV2AuthTokenRedeemPostAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2AuthTokenRedeemPostAsyncWithHttpInfo
     *
     * Pobranie tokenów dostępowych
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthTokenRedeemPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2AuthTokenRedeemPostAsyncWithHttpInfo(
        string $contentType = self::contentTypes['apiV2AuthTokenRedeemPost'][0]
    ): PromiseInterface
    {
        $returnType = '\NetSeven\KseF2Model\AuthenticationTokensResponse';
        $request = $this->apiV2AuthTokenRedeemPostRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2AuthTokenRedeemPost'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthTokenRedeemPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2AuthTokenRedeemPostRequest(
        string $contentType = self::contentTypes['apiV2AuthTokenRedeemPost'][0]
    ): Request
    {


        $resourcePath = '/api/v2/auth/token/redeem';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2AuthTokenRefreshPost
     *
     * Odświeżenie tokena dostępowego
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthTokenRefreshPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \NetSeven\KseF2Model\AuthenticationTokenRefreshResponse|\NetSeven\KseF2Model\ExceptionResponse
     */
    public function apiV2AuthTokenRefreshPost(
        string $contentType = self::contentTypes['apiV2AuthTokenRefreshPost'][0]
    ): \NetSeven\KseF2Model\AuthenticationTokenRefreshResponse|\NetSeven\KseF2Model\ExceptionResponse
    {
        list($response) = $this->apiV2AuthTokenRefreshPostWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation apiV2AuthTokenRefreshPostWithHttpInfo
     *
     * Odświeżenie tokena dostępowego
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthTokenRefreshPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \NetSeven\KseF2Model\AuthenticationTokenRefreshResponse|\NetSeven\KseF2Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2AuthTokenRefreshPostWithHttpInfo(
        string $contentType = self::contentTypes['apiV2AuthTokenRefreshPost'][0]
    ): array
    {
        $request = $this->apiV2AuthTokenRefreshPostRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\AuthenticationTokenRefreshResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NetSeven\KseF2Model\AuthenticationTokenRefreshResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\AuthenticationTokenRefreshResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation apiV2AuthTokenRefreshPostAsync
     *
     * Odświeżenie tokena dostępowego
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthTokenRefreshPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2AuthTokenRefreshPostAsync(
        string $contentType = self::contentTypes['apiV2AuthTokenRefreshPost'][0]
    ): PromiseInterface
    {
        return $this->apiV2AuthTokenRefreshPostAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2AuthTokenRefreshPostAsyncWithHttpInfo
     *
     * Odświeżenie tokena dostępowego
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthTokenRefreshPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2AuthTokenRefreshPostAsyncWithHttpInfo(
        string $contentType = self::contentTypes['apiV2AuthTokenRefreshPost'][0]
    ): PromiseInterface
    {
        $returnType = '\NetSeven\KseF2Model\AuthenticationTokenRefreshResponse';
        $request = $this->apiV2AuthTokenRefreshPostRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2AuthTokenRefreshPost'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthTokenRefreshPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2AuthTokenRefreshPostRequest(
        string $contentType = self::contentTypes['apiV2AuthTokenRefreshPost'][0]
    ): Request
    {


        $resourcePath = '/api/v2/auth/token/refresh';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2AuthXadesSignaturePost
     *
     * Uwierzytelnienie z wykorzystaniem podpisu XAdES
     *
     * @param  string $body body (required)
     * @param  bool|null $verify_certificate_chain Wymuszenie weryfikacji zaufania łańcucha certyfikatu wraz ze sprawdzeniem statusu certyfikatu (OCSP/CRL) na środowiskach które umożliwiają wykorzystanie samodzielnie wygenerowanych certyfikatów. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthXadesSignaturePost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \NetSeven\KseF2Model\AuthenticationInitResponse|\NetSeven\KseF2Model\ExceptionResponse
     */
    public function apiV2AuthXadesSignaturePost(
        string $body,
        ?bool $verify_certificate_chain = null,
        string $contentType = self::contentTypes['apiV2AuthXadesSignaturePost'][0]
    ): \NetSeven\KseF2Model\AuthenticationInitResponse|\NetSeven\KseF2Model\ExceptionResponse
    {
        list($response) = $this->apiV2AuthXadesSignaturePostWithHttpInfo($body, $verify_certificate_chain, $contentType);
        return $response;
    }

    /**
     * Operation apiV2AuthXadesSignaturePostWithHttpInfo
     *
     * Uwierzytelnienie z wykorzystaniem podpisu XAdES
     *
     * @param  string $body (required)
     * @param  bool|null $verify_certificate_chain Wymuszenie weryfikacji zaufania łańcucha certyfikatu wraz ze sprawdzeniem statusu certyfikatu (OCSP/CRL) na środowiskach które umożliwiają wykorzystanie samodzielnie wygenerowanych certyfikatów. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthXadesSignaturePost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \NetSeven\KseF2Model\AuthenticationInitResponse|\NetSeven\KseF2Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2AuthXadesSignaturePostWithHttpInfo(
        string $body,
        ?bool $verify_certificate_chain = null,
        string $contentType = self::contentTypes['apiV2AuthXadesSignaturePost'][0]
    ): array
    {
        $request = $this->apiV2AuthXadesSignaturePostRequest($body, $verify_certificate_chain, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\AuthenticationInitResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\NetSeven\KseF2Model\AuthenticationInitResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\AuthenticationInitResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\NetSeven\KseF2Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation apiV2AuthXadesSignaturePostAsync
     *
     * Uwierzytelnienie z wykorzystaniem podpisu XAdES
     *
     * @param  string $body (required)
     * @param  bool|null $verify_certificate_chain Wymuszenie weryfikacji zaufania łańcucha certyfikatu wraz ze sprawdzeniem statusu certyfikatu (OCSP/CRL) na środowiskach które umożliwiają wykorzystanie samodzielnie wygenerowanych certyfikatów. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthXadesSignaturePost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2AuthXadesSignaturePostAsync(
        string $body,
        ?bool $verify_certificate_chain = null,
        string $contentType = self::contentTypes['apiV2AuthXadesSignaturePost'][0]
    ): PromiseInterface
    {
        return $this->apiV2AuthXadesSignaturePostAsyncWithHttpInfo($body, $verify_certificate_chain, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2AuthXadesSignaturePostAsyncWithHttpInfo
     *
     * Uwierzytelnienie z wykorzystaniem podpisu XAdES
     *
     * @param  string $body (required)
     * @param  bool|null $verify_certificate_chain Wymuszenie weryfikacji zaufania łańcucha certyfikatu wraz ze sprawdzeniem statusu certyfikatu (OCSP/CRL) na środowiskach które umożliwiają wykorzystanie samodzielnie wygenerowanych certyfikatów. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthXadesSignaturePost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiV2AuthXadesSignaturePostAsyncWithHttpInfo(
        string $body,
        ?bool $verify_certificate_chain = null,
        string $contentType = self::contentTypes['apiV2AuthXadesSignaturePost'][0]
    ): PromiseInterface
    {
        $returnType = '\NetSeven\KseF2Model\AuthenticationInitResponse';
        $request = $this->apiV2AuthXadesSignaturePostRequest($body, $verify_certificate_chain, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2AuthXadesSignaturePost'
     *
     * @param  string $body (required)
     * @param  bool|null $verify_certificate_chain Wymuszenie weryfikacji zaufania łańcucha certyfikatu wraz ze sprawdzeniem statusu certyfikatu (OCSP/CRL) na środowiskach które umożliwiają wykorzystanie samodzielnie wygenerowanych certyfikatów. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2AuthXadesSignaturePost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2AuthXadesSignaturePostRequest(
        string $body,
        ?bool $verify_certificate_chain = null,
        string $contentType = self::contentTypes['apiV2AuthXadesSignaturePost'][0]
    ): Request
    {

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $body when calling apiV2AuthXadesSignaturePost'
            );
        }



        $resourcePath = '/api/v2/auth/xades-signature';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $verify_certificate_chain,
            'verifyCertificateChain', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
